version: '3'

services:

  server:
    image: 'fernandoremde/flower-federated:server'
    environment:
      - SERVER_IP=0.0.0.0:8080
    networks:
      - default
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==manager

  client1:
    image: 'fernandoremde/flower-federated:client1'
    environment:
      - SERVER_IP=fl_server:8080
    networks:
      default:
    restart: always
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.type==worker
 
  client2:
    image: 'fernandoremde/flower-federated:client2'
    environment:
      - SERVER_IP=fl_server:8080
    networks:
      default:
    restart: always
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.type==worker
 
networks:
  default:
