version: '3'

services:

  server:
    image: 'fernandoremde/flower-federated:server'
    environment:
      - SERVER_IP=0.0.0.0:8080
      - FRACTION_FIT=0.1
      - MIN_FIT_CLIENTS=10
      - MIN_AVAILABLE_CLIENTS=10
      - NUM_ROUNDS=10
    networks:
      - default
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==manager

  greenclient0:
    image: 'fernandoremde/flower-federated:green-client-0'
    environment:
      - SERVER_IP=fl_server:8080
      - KERNEL_SQUARE_CONVOLUTION=5
      - FIRST_FULLY_CONNECTED_LAYER=120
      - SECOND_FULLY_CONNECTED_LAYER=84
    networks:
      - default
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker

  greenclient1:
    image: 'fernandoremde/flower-federated:green-client-1'
    environment:
      - SERVER_IP=fl_server:8080
      - KERNEL_SQUARE_CONVOLUTION=5
      - FIRST_FULLY_CONNECTED_LAYER=120
      - SECOND_FULLY_CONNECTED_LAYER=84
    networks:
      - default
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker

  greenclient2:
    image: 'fernandoremde/flower-federated:green-client-2'
    environment:
      - SERVER_IP=fl_server:8080
      - KERNEL_SQUARE_CONVOLUTION=5
      - FIRST_FULLY_CONNECTED_LAYER=120
      - SECOND_FULLY_CONNECTED_LAYER=84
    networks:
      - default
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker

  greenclient3:
    image: 'fernandoremde/flower-federated:green-client-3'
    environment:
      - SERVER_IP=fl_server:8080
      - KERNEL_SQUARE_CONVOLUTION=5
      - FIRST_FULLY_CONNECTED_LAYER=120
      - SECOND_FULLY_CONNECTED_LAYER=84
    networks:
      - default
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker

  greenclient4:
    image: 'fernandoremde/flower-federated:green-client-4'
    environment:
      - SERVER_IP=fl_server:8080
      - KERNEL_SQUARE_CONVOLUTION=5
      - FIRST_FULLY_CONNECTED_LAYER=120
      - SECOND_FULLY_CONNECTED_LAYER=84
    networks:
      - default
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker

  greenclient5:
    image: 'fernandoremde/flower-federated:green-client-5'
    environment:
      - SERVER_IP=fl_server:8080
      - KERNEL_SQUARE_CONVOLUTION=5
      - FIRST_FULLY_CONNECTED_LAYER=120
      - SECOND_FULLY_CONNECTED_LAYER=84
    networks:
      - default
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker

  greenclient6:
    image: 'fernandoremde/flower-federated:green-client-6'
    environment:
      - SERVER_IP=fl_server:8080
      - KERNEL_SQUARE_CONVOLUTION=5
      - FIRST_FULLY_CONNECTED_LAYER=120
      - SECOND_FULLY_CONNECTED_LAYER=84
    networks:
      - default
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker

  greenclient7:
    image: 'fernandoremde/flower-federated:green-client-7'
    environment:
      - SERVER_IP=fl_server:8080
      - KERNEL_SQUARE_CONVOLUTION=5
      - FIRST_FULLY_CONNECTED_LAYER=120
      - SECOND_FULLY_CONNECTED_LAYER=84
    networks:
      - default
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker

  greenclient8:
    image: 'fernandoremde/flower-federated:green-client-8'
    environment:
      - SERVER_IP=fl_server:8080
      - KERNEL_SQUARE_CONVOLUTION=5
      - FIRST_FULLY_CONNECTED_LAYER=120
      - SECOND_FULLY_CONNECTED_LAYER=84
    networks:
      - default
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker

  greenclient9:
    image: 'fernandoremde/flower-federated:green-client-9'
    environment:
      - SERVER_IP=fl_server:8080
      - KERNEL_SQUARE_CONVOLUTION=5
      - FIRST_FULLY_CONNECTED_LAYER=120
      - SECOND_FULLY_CONNECTED_LAYER=84
    networks:
      - default
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker

  observer:
    image: 'fernandoremde/flower-federated:observer'
    environment:
      - EXPERIMENT_NAME=green
    networks:
      - default
    restart: always
    volumes:
      - "~/reports:/reports"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==manager

 
networks:
  default:
